#!/usr/bin/env python3
"""
Generate SDVX song data for the Archipelago world package.

Usage:
    python generate_song_data.py <path_to_music_db.xml> <output_data.py>

Example:
    python generate_song_data.py "Z:\\AP nans\\music_db.xml" ^
        "C:\\ProgramData\\Archipelago\\lib\\worlds\\sdvx\\data.py"
"""
import sys
import xml.etree.ElementTree as ET
from pathlib import Path


DIFF_ORDER = ('novice', 'advanced', 'exhaust', 'infinite', 'maximum')

# AP difficulty index and short label for each XML difficulty element name.
# infinite and maximum both map to index 3; whichever appears first is used.
DIFF_META = {
    'novice':   (0, 'NOV'),
    'advanced': (1, 'ADV'),
    'exhaust':  (2, 'EXH'),
    'infinite': (3, 'INF'),
    'maximum':  (3, 'MXM'),
}

ITEM_BASE_ID     = 8_000_000   # items:     8000000 – 8099999  (100 000 slots)
LOCATION_BASE_ID = 8_100_000   # locations: 8100000 + music_id*10 + diff


def parse_music_db(xml_path: str):
    """Parse music_db.xml and return a list of song dicts."""
    # expat (Python 3.14+) dropped multi-byte encoding support, so we decode
    # the raw bytes as shift-jis first, rewrite the XML declaration to UTF-8,
    # then feed the resulting Unicode string to the parser.
    raw = Path(xml_path).read_bytes()
    text = raw.decode('shift-jis', errors='replace')
    text = text.replace('encoding="shift-jis"', 'encoding="utf-8"', 1)
    root = ET.fromstring(text.encode('utf-8'))

    songs = []
    for music in root.findall('music'):
        mid = int(music.get('id'))

        info = music.find('info')
        if info is None:
            continue

        title    = (info.findtext('title_name') or '').strip()
        ascii_id = (info.findtext('ascii') or '').strip()

        # Fallback chain for display name
        display = title or ascii_id or f'Song {mid}'

        diffs = []
        seen_idx3 = False
        difficulty_el = music.find('difficulty')
        if difficulty_el is not None:
            for diff_name in DIFF_ORDER:
                d = difficulty_el.find(diff_name)
                if d is None:
                    continue
                difnum_el = d.find('difnum')
                if difnum_el is None or not (difnum_el.text or '').strip():
                    continue
                dn = int(difnum_el.text)
                if dn <= 0:
                    continue
                idx, label = DIFF_META[diff_name]
                if idx == 3:
                    if seen_idx3:
                        continue   # skip duplicate 4th-diff entry
                    seen_idx3 = True
                diffs.append((idx, label, dn))

        if diffs:
            songs.append({
                'id':      mid,
                'ascii':   ascii_id,
                'title':   display,
                'diffs':   diffs,
            })

    return songs


def build_location_table(songs):
    """Return ({location_name: location_id}, {location_name: diff_level}) with collision detection."""
    table = {}
    levels = {}
    seen_names = {}

    for song in songs:
        mid   = song['id']
        title = song['title']
        for diff_idx, diff_label, level in song['diffs']:
            name = f'{title} [{diff_label}]'
            loc_id = LOCATION_BASE_ID + mid * 10 + diff_idx

            # Resolve name collisions by appending the music ID
            if name in seen_names and seen_names[name] != mid:
                name = f'{title} (id{mid}) [{diff_label}]'
            seen_names[name] = mid

            table[name] = loc_id
            levels[name] = level

    return table, levels


def write_data_py(songs, location_table, location_levels, output_path: str):
    total_locs = len(location_table)

    def esc(s):
        return s.replace('\\', '\\\\').replace("'", "\\'")

    lines = [
        '# Auto-generated by tools/generate_song_data.py from music_db.xml',
        '# DO NOT EDIT MANUALLY — re-run the script to update.',
        '',
        'from typing import Dict, List, Tuple',
        '',
        f'LOCATION_BASE_ID: int = {LOCATION_BASE_ID}',
        f'ITEM_BASE_ID: int     = {ITEM_BASE_ID}',
        '',
        '# Each entry: (music_id, ascii_id, display_title, [(diff_index, diff_label, diff_level), ...])',
        '# diff_index: 0=NOV  1=ADV  2=EXH  3=INF/MXM  |  diff_level: 1-20',
        'SONGS: List[Tuple[int, str, str, List[Tuple[int, str, int]]]] = [',
    ]

    for song in songs:
        lines.append(
            f"    ({song['id']}, '{esc(song['ascii'])}', "
            f"'{esc(song['title'])}', {song['diffs']!r}),"
        )

    lines += [
        ']',
        '',
        f'# {total_locs} locations total',
        '# location_id = LOCATION_BASE_ID + music_id * 10 + diff_index',
        'LOCATION_TABLE: Dict[str, int] = {',
    ]

    for loc_name, loc_id in location_table.items():
        lines.append(f"    '{esc(loc_name)}': {loc_id},")

    lines += [
        '}',
        '',
        '# Maps each location name to its chart difficulty level (1-20)',
        'LOCATION_LEVEL: Dict[str, int] = {',
    ]

    for loc_name, level in location_levels.items():
        lines.append(f"    '{esc(loc_name)}': {level},")

    lines += ['}', '']

    Path(output_path).write_text('\n'.join(lines), encoding='utf-8')


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)

    xml_path, out_path = sys.argv[1], sys.argv[2]

    print(f'Parsing {xml_path} ...')
    songs = parse_music_db(xml_path)
    location_table, location_levels = build_location_table(songs)

    print(f'Writing {out_path} ...')
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    write_data_py(songs, location_table, location_levels, out_path)

    total_locs = len(location_table)
    print(f'Done — {len(songs)} songs, {total_locs} locations')


if __name__ == '__main__':
    main()
