name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: build.bat
        shell: cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdvx-ap-${{ github.sha }}
          path: deploy/
          if-no-files-found: error
